### ISSUE TITLE
CI requirements

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/go-intelowl#9]
We should try to follow the same workflow of all the other projects:
* using master branch only for pushing new releases from the develop branch
* using develop branch as base repository and create new branches for new features from this branch
* adding linters for go code
* configure dependabot correctly
* enable code-ql for go
* enable them in github actions
* others I could have missed

**Comment by CITIZENDOT** [comment]
Rather than starting from scratch, [This](https://github.com/jandelgado/golang-ci-template-github-actions) could be a reference for contributors. 
It includes (with minor changes)
- using master branch only for pushing new releases from the develop branch
- using develop branch as base repository and create new branches for new features from this branch
- adding linters for go code
- Running tests

And **also Code Coverage**

**Comment by spiderxm** [comment]
Assign me this issue

**Comment by spiderxm** [comment]
@mlodic, @Eshaan7. Please create a develop branch. Then in future will raise pr only in develop branch.

**Comment by eshaan7** [comment]
> @mlodic, @Eshaan7. Please create a develop branch. Then in future will raise pr only in develop branch.
> 

I think we can create a develop branch once we have atleast a working prototype and the first alpha release of this.
No point in managing 2 branches for now.
